import argparse
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "packages/shared/schema/account-brief.schema.json"
TYPES_PATH = ROOT / "packages/shared/src/generated/account-brief.ts"

sys.path.insert(0, str(ROOT))

from apps.api.schemas import AccountBrief  # noqa: E402


def schema_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]

    if "anyOf" in schema:
        return " | ".join(schema_type(option) for option in schema["anyOf"])

    if schema.get("type") == "array":
        return f"Array<{schema_type(schema['items'])}>"

    if schema.get("type") == "string":
        return "string"

    if schema.get("type") == "null":
        return "null"

    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])

    if schema.get("type") in {"number", "integer"}:
        return "number"

    if schema.get("type") == "object":
        properties = schema.get("properties", {})
        fields = [
            f"  {name}: {schema_type(property_schema)};"
            for name, property_schema in properties.items()
        ]
        return "{\n" + "\n".join(fields) + "\n}"

    raise ValueError(f"Unsupported JSON Schema node: {schema}")


def render_types(schema: dict[str, Any]) -> str:
    definitions = schema.get("$defs", {})
    blocks = [
        f"export type {name} = {schema_type(definition)};"
        for name, definition in definitions.items()
    ]
    blocks.append(f"export type AccountBrief = {schema_type(schema)};")
    return "// Generated by scripts/generate_shared_types.py. Do not edit.\n\n" + "\n\n".join(blocks) + "\n"


def write_or_check(path: Path, content: str, check: bool) -> None:
    current = path.read_text() if path.exists() else None

    if check:
        if current != content:
            raise SystemExit(f"Generated file is stale: {path.relative_to(ROOT)}")
        return

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    schema = AccountBrief.model_json_schema()
    schema_content = json.dumps(schema, indent=2) + "\n"
    types_content = render_types(schema)

    write_or_check(SCHEMA_PATH, schema_content, args.check)
    write_or_check(TYPES_PATH, types_content, args.check)


if __name__ == "__main__":
    main()